In [3]:
import numpy as np

# 1. Create a null vector of size 10 but the fifth value which is 1
null_vector = np.zeros(10)
null_vector[4] = 1
null_vector


array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [4]:
# 2. Create a vector with values ranging from 10 to 49
vector_range_10_to_49 = np.arange(10, 50)
vector_range_10_to_49

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [5]:
# 3. Reverse a vector
reversed_vector = vector_range_10_to_49[::-1]
reversed_vector

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

In [7]:
# 4. Create a 3x3 matrix with values ranging from 0 to 8
matrix_3x3 = np.arange(9).reshape(3, 3)
matrix_3x3

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [6]:
# 5. Find indices of non-zero elements from [1,2,0,0,4,0]
arr = np.array([1, 2, 0, 0, 4, 0])
non_zero_indices = np.nonzero(arr)
non_zero_indices


(array([0, 1, 4]),)

In [8]:
# 6. Create a 3x3x3 array with random values
random_3x3x3_array = np.random.rand(3, 3, 3)
random_3x3x3_array

array([[[0.61576248, 0.09381922, 0.2064676 ],
        [0.43721146, 0.93029587, 0.20770061],
        [0.37268753, 0.59672505, 0.52502689]],

       [[0.66265537, 0.75006707, 0.72474491],
        [0.66030851, 0.8173317 , 0.84500106],
        [0.08315913, 0.2119418 , 0.375379  ]],

       [[0.02460129, 0.23322359, 0.34822092],
        [0.76321639, 0.25883579, 0.8136794 ],
        [0.23695306, 0.53826239, 0.61885518]]])

In [ ]:
# 7. Create a 10x10 array with random values and find the minimum and maximum values
random_10x10_array = np.random.rand(10, 10)
min_value = random_10x10_array.min()
max_value = random_10x10_array.max()
min_val